// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"=============================","status":false,"description":"=========================================================================","parameters":{}},
{"name":"NUUN_Base","status":true,"description":"NuuNBasePlugin","parameters":{}},
{"name":"NUUN_PartyCommandCustomize","status":true,"description":"パーティコマンドカスタマイズ","parameters":{"PartyCommandList":"[]"}},
{"name":"=============================","status":false,"description":"=========================================================================","parameters":{}},
{"name":"SS_Custom_Formulas","status":true,"description":"Allows defining multiple named damage formulas as an array.","parameters":{"formulas":"[]"}},
{"name":"PluginCommonBase","status":true,"description":"Plugin Analysis Common Base","parameters":{}},
{"name":"CommandSkill","status":false,"description":"コマンドスキルプラグイン","parameters":{"index":"1","includeMenu":"false","showHelp":"false","showHelpAlways":"true","showCost":"false"}},
{"name":"Keke_VariableActorCommand","status":true,"description":"アクターコマンドを自在に組み替える","parameters":{"window":"","window auto-stretch":"true","window stretch bottom edge":"616","window opacity":"255","icon":"","icon display":"true","icon size":"32","icon X position":"-4","Icon Y Position":"0","Icon Placement":"Left","Touch Button":"","Cancel Button Auto Move":"Place Top","Help":"","Help Registration":"[]","Show skill help":"true","Other":"","Disable party commands":"true","Reference skills in commands.":"true","Terminology/Auto Battle":"Auto"}}
];
