// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"=============================","status":true,"description":"=========================================================================","parameters":{}},
{"name":"NUUN_Base","status":true,"description":"NuuNBasePlugin","parameters":{}},
{"name":"NUUN_PartyCommandCustomize","status":true,"description":"パーティコマンドカスタマイズ","parameters":{"PartyCommandList":"[]"}},
{"name":"=============================","status":true,"description":"=========================================================================","parameters":{}},
{"name":"SS_Custom_Formulas","status":true,"description":"Allows defining multiple named damage formulas as an array.","parameters":{"formulas":"[]"}}
];
